# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/publishing-docker-images
# https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md
name: unit-testing
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        perl: [ '5.34', '5.32', '5.16.3' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: apt-get
        run:  |
          sudo apt-get install ncbi-blast+ bowtie2 samtools libdb-dev libberkeleydb-perl libgd-dev libcdb-file-perl
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm
          install-modules-args: --force
          enable-modules-cache: true
          install-modules: DB_File::HASHINFO Bio::Tools::GuessSeqFormat File::chdir File::Which
      #- run: yes no | sudo $(which cpanm) -l local --installdeps --force
      #- run: yes no | sudo $(which cpanm) -l local Bio::Tools::GuessSeqFormat File::chdir File::Which --force
      - name: versions
        run:  |
          bowtie2 --version && echo
          samtools --version && echo
          blastn -version && echo
      - run: perl -V
      - name: make test
        run: perl Makefile.PL && make && make test
      #- run: prove -lv t
